all:
	g++ main.cpp picture.cpp string_pic.cpp frame_pic.cpp hcat_pic.cpp vcat_pic.cpp -g

main.o:
	g++ -c main.cpp

picture.o:
	g++ -c picture.cpp

string_pic.o:
	g++ -c string_pic.cpp

frame_pic.o:
	g++ -c frame_pic.cpp

hcat_pic.o:
	g++ -c hcat_pic.cpp

vcat_pic.o:
	g++ -c vcat_pic.cpp

clean:
	rm *.o a.out
