picture:
	g++ main_pic.cpp picture.cpp string_pic.cpp frame_pic.cpp hcat_pic.cpp vcat_pic.cpp -o picture

student: main_student.cpp core.cpp grad.cpp student_calc.cpp student_info.cpp
	g++ grad.cpp core.cpp student_calc.cpp student_info.cpp main_student.cpp -o student

all:
	g++ main.cpp picture.cpp string_pic.cpp frame_pic.cpp hcat_pic.cpp vcat_pic.cpp grad.cpp core.cpp student_calc.cpp student_info.cpp
