all: main.cpp core.cpp core.hpp grad.cpp grad.hpp student_calc.cpp student_calc.hpp student_info.cpp student_info.hpp
	g++ grad.cpp core.cpp student_calc.cpp student_info.cpp pass.cpp audit.cpp main.cpp 
